// frontend/src/utils/reportGenerator.ts
import ReportHeader from "../components/reports/ReportHeader";
import ReportFooter from "../components/reports/ReportFooter";
import { getReportStyles } from "../components/reports/ReportStyles";

interface ReportData {
  title: string;
  subtitle?: string;
  reportType?: string;
  sections: Array<{
    title: string;
    subtitle?: string;
    headers: string[];
    rows: Array<Array<string | number>>;
    summary?: string;
  }>;
  totalRecords?: number;
  additionalInfo?: {
    totalStudents?: number;
    academicYear?: string;
    generatedBy?: string;
  };
}

export const generateReport = (data: ReportData) => {
  const {
    title,
    subtitle = "Official Administrative Report",
    reportType = "Comprehensive Report",
    sections,
    totalRecords,
    additionalInfo = {}
  } = data;

  const generatedDate = new Date();
  const { totalStudents = totalRecords, academicYear = new Date().getFullYear().toString(), generatedBy = "Administration Office" } = additionalInfo;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - Northbridge University</title>
      <meta charset="UTF-8">
      ${getReportStyles()}
      ${ReportHeader({ title, subtitle, generatedDate, reportType })}
      ${ReportFooter({})}
    </head>
    <body>
      <!-- Header -->
      ${ReportHeader({ title, subtitle, generatedDate, reportType })}
      
      <!-- Info Bar -->
      <div class="info-bar">
        <span><strong>Total Records:</strong> ${totalStudents || sections.reduce((acc, section) => acc + section.rows.length, 0)}</span>
        <span><strong>Report Type:</strong> ${reportType}</span>
        <span><strong>Academic Year:</strong> ${academicYear}</span>
        <span><strong>Generated By:</strong> ${generatedBy}</span>
      </div>
      
      <!-- Report Sections -->
      ${sections.map(section => `
        <div class="student-section">
          <div class="section-header">
            <h3>${section.title}</h3>
            ${section.subtitle ? `<p>${section.subtitle}</p>` : ''}
          </div>
          
          <table>
            <thead>
              <tr>
                ${section.headers.map(header => `<th>${header}</th>`).join('')}
              <table>
            </thead>
            <tbody>
              ${section.rows.map(row => `
                <tr>
                  ${row.map(cell => `<td>${cell || '-'}</td>`).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>
          
          ${section.summary ? `<div class="summary-row">${section.summary}</div>` : ''}
        </div>
      `).join('')}
      
      <!-- Footer -->
      ${ReportFooter({})}
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.print();
  printWindow.close();
};